spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update